from . import hr_ec_payroll_period
from . import hr_ec_payroll_input
from . import hr_ec_payroll_input_type
from . import hr_ec_payroll_payslip
from . import hr_employee
from . import res_company
from . import res_partner
from . import hr_service_contract
from . import hr_th_summary
