{
    "name": "Gestión de servicios TH",
    "version": "17.0.2.0.0",
    "category": "Human Resources",
    "summary": "Contratos de servicio, clientes TH y colaboradores de clientes",
    "author": "Consultora TH",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "contacts",
        "crm",
        "sale_management",
        "project",
        "account",
        "hr",
        "l10n_ec",
    ],
    "data": [
        "security/hr_service_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/hr_service_document_section_data.xml",
        "data/mail_activity_type_data.xml",
        "data/project_task_template_data.xml",
        "views/hr_service_contract_views.xml",
        "views/hr_service_document_views.xml",
        "views/hr_th_dashboard_views.xml",
        "views/res_partner_views.xml",
        "views/hr_employee_views.xml",
        "views/project_project_views.xml",
        "views/hr_service_menus.xml",
        "wizard/hr_service_payroll_period_wizard_views.xml",
    ],
    "demo": [
        "demo/demo_data.xml",
        "demo/demo_operational.xml",
    ],
    "installable": True,
    "application": True,
}
